# Corso di Probabilità e Statistica 
## Vettori, matrici, numeri random
In questo capitolo introduciamo alcuni concetti elementari sulla generazione di vettori e matrici e numeri casuali. 

In [1]:
# importare packages
import numpy as np #operazioni numeriche

### Generare numeri random

generare un numero random in [0,1]

In [2]:
x_u=np.random.rand()
x_u
print(x_u)

0.26433444668261763


generare un numero random Gaussiano (media =0 varianza=1)

In [3]:
x_g=np.random.randn() #random normal, ovviamente centrata in 0 e con varianza 1
x_g
print(x_g)

2.0913180255171806


generare un numero random Gaussiano (media =m varianza=s)

In [4]:
m=1
s=2
x_g=s*np.random.randn()+m #rinormalizzo la gaussiana di prima
print(x_g)

-0.031657840751535105


Generare numero random con distribuzione esponenziale

In [5]:
x=np.random.rand() #numero random uniforme
r0=2
y_e=-np.log(1-x)/r0 #utilizzo l'inversa della cumulativa
print(y_e)

1.2790703402070338


### Generare vettori

generare i numeri tra a e b, spaziati di d

In [6]:
a=1
b=5
d=0.5
x = np.arange(a,b,d)
# <vector_name> = np.arange(#min, #max, #distance)

In [7]:
print(x)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5]


generare N numeri equispaziati tra a e b (inclusi)

In [8]:
a=0
b=1
N=11
y = np.linspace(a,b,N) 
#linspace è uguale ad arange con la differenza che, anzichè fissare la distanza fisso il numero di punti q poi questi vengono automaticamente equispaziati

In [9]:
print(y)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [10]:
#vettore di N componenti inizializzate 0
N=3
zero_vector = np.zeros(N)
print(zero_vector)

[0. 0. 0.]


In [11]:
#vettore di N componenti random Gaussiane
N=3
random_vector = np.random.randn(N) #genero tre elementi distribuiti secondo una gaussiana
print(random_vector)

[-0.93759451  0.80836902 -0.64052562]


In [15]:
#vettore di N componenti distribuite normalmente però con una gaussiana diversa da N(0,1)
I = len(random_vector)

for i in range(I):
    random_vector[i] = s*random_vector[i] + m
    
random_vector

array([-0.75037803,  6.2334761 ,  0.4378975 ])

### Generare matrici 

In [14]:
#matrice NxM =0
N=3
M=4
zero_matrix = np.zeros((N,M))
zero_matrix

#eventualmente a questo punto posso anche generare un tensore NxMxL ad esempio, solo non avrebbe molto senso stamparlo
#formalmente, per il linguaggio questo è un vettore in cui ciascun elemento è un vettore di 3 elementi
#solo che python fa schifo e scrive i vettori in orizzontale anzichè in verticale

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
#matrice NxM =1
N=3
M=4
one_matrix = np.ones((N,M))
one_matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
#matrice random NxM  (numeri casuali ma distribuiti secondo una gaussiana N(0,1))
N=3
M=4
random_matrix=np.random.randn(N,M)
random_matrix

array([[ 0.57812036, -0.59919787,  0.10209246,  1.50041944],
       [ 0.50774349,  0.06777477,  0.08079973,  0.38586451],
       [ 2.21798615, -2.16260126, -0.90762564,  0.46198863]])

Selezionare elementi di vettori o matrici

In [21]:
random_matrix[2,1] 
#dato che gli indici partono da 0 sto guardando la 3a riga, 2a colonna

-2.1626012648287145

In [20]:
random_matrix[0,0]

0.5781203638560124

Selezionare colonna

In [23]:
random_matrix[:,1]
#in pratica vincolo la colonna, in questo caso la seconda, e faccio variare la riga

array([-0.59919787,  0.06777477, -2.16260126])

Selezionare riga

In [24]:
random_matrix[2,:]
#in pratica vincolo la riga, in questo caso la terza, lasciando il vincolo della colonna

array([ 2.21798615, -2.16260126, -0.90762564,  0.46198863])

#### Esercizio

1) generare una matrice di dimensione 5x5 i cui elementi siano numeri random distribuiti tra [-1,1]

2) Selezionare la terza riga 

In [19]:
#genero matrice 5x5
N = 5
M = 5
es_unif = np.random.rand(N,M)

massimo = +1
minimo = -1

for i in range(N):
    for j in range(M):
        es_unif[i,j] = es_unif[i,j]*(massimo-minimo) + minimo

es_unif

array([[ 0.34830064, -0.62042407, -0.99191791,  0.2361518 ,  0.13355793],
       [-0.6001005 , -0.17829222,  0.179903  ,  0.48122383, -0.98490561],
       [ 0.37599413, -0.42606939, -0.00825098, -0.24325944, -0.0394724 ],
       [-0.00939471,  0.79538706, -0.69156364,  0.02217823,  0.18356791],
       [ 0.54515095, -0.98387879, -0.48954914,  0.64680036,  0.52611173]])

In [34]:
#seleziono la terza riga
#vincolo la riga con indice 2 e faccio variare la colonna
es_unif[2,:]

array([0.60185117, 0.14410988, 0.03703065, 0.13926171, 0.35455907])

## Analisi statistica

### distribuzione uniforme

In [25]:
x10=np.random.rand(10) #10 numeri estratti su [0,1]
x100=np.random.rand(100) #100 numeri estratti su [0,1]
x1000=np.random.rand(1000) #1000 numeri estratti su [0,1]

print(x10)

[0.47212144 0.96830474 0.09371951 0.37337349 0.84395154 0.89830158
 0.10889821 0.60685277 0.29191811 0.77731078]


In [26]:
# media
mu10=np.mean(x10)
mu100=np.mean(x100)
mu1000=np.mean(x1000)

print(mu10)
print(mu100)
print(mu1000)

0.5434752181051927
0.4923957460416669
0.5036824728090976


Dai risultati stampati sopra si osserva che all'aumentare di numeri estratti il valor medio della distribuzione si avvicina al valor medio teorico

In [27]:
# mediana
m10=np.median(x10)
m100=np.median(x100)
m1000=np.median(x1000)

In [28]:
m10,m100,m1000

(0.5394871071270466, 0.49931035651493233, 0.4961928044830069)

In [29]:
# deviazione standard
sigma10=np.std(x10)
sigma100=np.std(x100)
sigma1000=np.std(x1000)

In [30]:
sigma10,sigma100,sigma1000

(0.30721458083735187, 0.28653700287865924, 0.28955906253010494)

Dai risultati stampati sopra si osserva che all'aumentare del numero di estrazioni la deviazione standard diminuisce

In [31]:
#varianza
sigma_2_10=np.var(x10)
sigma_2_100=np.var(x100)
sigma_2_1000=np.var(x1000)

In [32]:
sigma_2_10,sigma_2_100,sigma_2_1000

(0.09438079867906982, 0.08210345401868478, 0.08384445069331323)

Anche in questo caso si osserva che all'aumentare del numero di estrazioni la varianza (sigma2) diminuisce

In [33]:
# minimo e massimo

#funzione che restituisce il massimo in un set di numeri estratti
min10=np.amin(x10)
min100=np.amin(x100)
min1000=np.amin(x1000)

#funzione che restituisce il massimo in un set di numeri estratti
max10=np.amax(x10)
max100=np.amax(x100)
max1000=np.amax(x1000)

In [34]:
min10,min100,min1000,max10,max100,max1000

(0.0937195143988897,
 0.004811563650017225,
 0.00148691806004142,
 0.9683047427881276,
 0.9996767401146279,
 0.9993126291831022)

### Distribuzione esponenziale

In [35]:
N=1000
x=np.random.rand(N) #numero random uniforme
r0=2
y=-np.log(1-x)/r0

In [36]:
m=np.mean(y)
var=np.var(y)
std=np.std(y)
m,var,std

(0.5067566191337555, 0.2844554278769539, 0.533343630201912)

per una distribuzione esponenziale la media è uguale alla deviazione standard